### ISSUE TITLE
Install directories

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/Geant4GammaGammaAngularCorrelations10.01#1]
The PDF ReadMe says "these new modified classes must overwrite the existing classes in the source directory of Geant4" then gives an example location. I have the example directory, but there are no similar files in that directory. Searching for "G4RadioactiveDecay.cc" with `find` over the entire build produces no result. I can though, find an executable with similar name: `source/processes/CMakeFiles/G4processes.dir/hadronic/models/radioactive_decay/src/G4RadioactiveDecay.cc.o`. Where should I install the files that are given in this software package?

I'm using Geant 4.10.01.p01 on a TRIUMF Centos6 computer.

**Comment by evan012345** [comment]
Sounds like you haven't installed the Geant4 data files in your installation. The G4RadioactiveDecay and G4PhotonEvaporation data files are required, but you mind as well install all optional data files. See http://geant4.web.cern.ch/geant4/support/download.shtml, under "data files". If you have the space on your machine, you mind as well install them all, it can't hurt and they might come in handy later. 

The Geant4GammaGammaAngularCorrelations10.01 works on version 10.1. I haven't looked at supporting the patch yet. I will do that in the near future. To be safe right now, I would suggest using version 10.1, not 10.1.p01.

**Comment by SmithJK** [comment]
When I installed Geant4, I did set `-DGEANT4_INSTALL_DATA=ON`. The files that you indicated do not contain `G4RadioactiveDecay.cc` or `G4PhotonEvaporation.cc`. They do contain a lot of data files for each nucleus. Copies of these data files are already located in my Geant4 installation in `share/Geant4-10.1.1/data/RadioactiveDecay4.2/` and `share/Geant4-10.1.1/data/PhotonEvaporation3.1/`, but once again, there is no `G4RadioactiveDecay.cc` or `G4PhotonEvaporation.cc`.

As for utilizing the patch, is there a link to the unpatched version on Geant4's site that I'm missing? The current release has the patch included and the source archive only includes 10.0, not 10.1.

**Comment by evan012345** [comment]
Where are you looking for G4RadioactiveDecay.cc and G4PhotonEvaporation.cc? The source files should be somewhere like "/usr/local/src/geant4.10.01.p01/source/...". The data files for each nucleus are NOT located in the source directory, or at least they shouldn't be located there. My data files are found here "/usr/local/geant4.10.01.p01/share/Geant4-10.1.1/data/...". Notice the difference "/usr/local/src/geant4.10.01.p01/" and "usr/local/geant4.10.01.p01/", the one with "src" should be where your G4RadioactiveDecay.cc and G4PhotonEvaporation.cc. are located if you've installed these packages. 

My full path to G4RadioactiveDecay.cc is /usr/local/src/geant4.10.01.p01/source/processes/hadronic/models/radioactive_decay/src/G4RadioactiveDecay.cc. And to G4PhotonEvaporation.cc  my path is /usr/local/src/geant4.10.01.p01/source/processes/hadronic/models/de_excitation/photon_evaporation/src/G4PhotonEvaporation.cc. Your path might be different depending on how you installed Geant4.

I just made some modifications to the angular correlations code, I've confirmed that it works with the new patch. Please use the new "patched" repo Geant4GammaGammaAngularCorrelations10.01.p01 if you are using 10.1.p01.

**Comment by SmithJK** [comment]
Found the files. I was looking all over the build and install directories, but not in the source directory, because it was on another computer.

Thanks for the help, Evan.
