### ISSUE TITLE
Geant 10.02

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/Geant4GammaGammaAngularCorrelations10.01#2]
Has anyone tried this addition on Geant 10.02? I thought I'd give it a whirl and I'm getting a funky error message that doesn't make a lot of sense: it's yelling about something that isn't changed when we overwrite the files.

**Comment by AndrewMac1** [comment]
Yes, they have completely changed the photon evaporation classes so Evan's hack does not work with this version. The good thing is they have implemented their own version angular correlations which I will be asking many questions about in a few weeks once I get to the workshop.

**Comment by SmithJK** [comment]
Thanks - I look forward to hearing about their answers.
